<?php
require_once '../includes/auth.php';
require_once '../includes/generate_qr_codes.php';

// Only allow admin
requireRole('admin', '../login.php');
touchActivity(600, '../login.php');

$stmt = $pdo->prepare("SELECT fullname, office FROM users WHERE id = ?");
$stmt->execute([$_SESSION['user_id']]);
$user = $stmt->fetch();

// Fetch student assistants only in admin's office
$stmt = $pdo->prepare("SELECT id, fullname, username, email, status, created_at FROM users WHERE role = 'student' AND office = ?");
$stmt->execute([$user['office']]);
$students = $stmt->fetchAll();

// Fetch today's QR codes per office student (generated by cron or admin)
$qrByStudent = [];
foreach ($students as $s) {
  $qrByStudent[$s['id']] = getDailyQrCodes(date('Y-m-d'), $s['id'])[$s['id']] ?? ['name' => $s['fullname'], 'qrs' => []];
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Admin Dashboard - MySchedMate</title>
  <script src="https://cdn.tailwindcss.com"></script>
  <script src="https://unpkg.com/lucide@latest"></script>
  <script>
    tailwind.config = { darkMode: 'class' };
  </script>
</head>
<body class="bg-blue-50 dark:bg-gray-900 text-black dark:text-white min-h-screen">

<!-- Navbar -->
<nav class="bg-blue-700 dark:bg-gray-800 text-white px-6 py-3 flex items-center justify-between shadow">
  <div class="flex items-center space-x-2">
    <i data-lucide="user-cog" class="w-6 h-6"></i>
    <span class="text-lg font-bold">Admin Panel</span>
  </div>
  <div class="space-x-4 flex items-center">
    <span class="text-sm hidden sm:inline">Welcome, <?= htmlspecialchars($_SESSION['username']) ?>!</span>
    <a href="dashboard.php" class="hover:underline">Dashboard</a>
    <a href="../logout.php" class="hover:underline">Logout</a>
    <button id="theme-toggle">
      <i id="theme-icon" data-lucide="moon" class="w-5 h-5 hover:scale-110 transition duration-300"></i>
    </button>
  </div>
</nav>

<!-- Main Content -->
<main class="p-6 max-w-6xl mx-auto space-y-6">
  <h2 class="text-2xl font-semibold">Admin Dashboard</h2>
  <p class="text-sm">Name: <strong><?= htmlspecialchars($user['fullname']) ?></strong></p>
  <p class="text-sm mb-4">Office: <strong><?= htmlspecialchars($user['office']) ?></strong></p>

  <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
   <a href="generate_qr.php" class="bg-white dark:bg-gray-800 p-5 rounded-xl shadow-md hover:scale-105 transition duration-300 flex items-center space-x-3">
  <i data-lucide="qr-code" class="w-5 h-5 text-blue-600 dark:text-yellow-400"></i>
  <span>Generate QR Code</span>
</a>


    <a href="manage_requests.php" class="bg-white dark:bg-gray-800 p-5 rounded-xl shadow-md hover:scale-105 transition duration-300 flex items-center space-x-3">
      <i data-lucide="check-circle" class="w-5 h-5 text-blue-600 dark:text-yellow-400"></i>
      <span>Make-Up Requests</span>
    </a>

    <a href="reports.php" class="bg-white dark:bg-gray-800 p-5 rounded-xl shadow-md hover:scale-105 transition duration-300 flex items-center space-x-3">
      <i data-lucide="bar-chart-3" class="w-5 h-5 text-blue-600 dark:text-yellow-400"></i>
      <span>Reports</span>
    </a>
  </div>

  <div class="mt-8">
    <h3 class="text-xl font-semibold mb-4">🛡️ Today's QR Codes (<?= date('F j, Y') ?>)</h3>
    <?php
    $qrFilesExist = false;
    foreach ($qrByStudent as $student) {
      foreach ($student['qrs'] as $qr) {
        if ($qr['code'] && file_exists($qr['file'])) { $qrFilesExist = true; break 2; }
      }
    }
    ?>

    <?php if ($qrFilesExist): ?>
      <?php foreach ($qrByStudent as $studentId => $student): ?>
        <?php
        $studentHasQr = false;
        foreach ($student['qrs'] as $qr) {
          if ($qr['code'] && file_exists($qr['file'])) { $studentHasQr = true; break; }
        }
        ?>
        <?php if ($studentHasQr): ?>
          <div class="mb-6">
            <h4 class="font-semibold mb-2 text-blue-700 dark:text-yellow-400">🎓 <?= htmlspecialchars($student['name']) ?></h4>
            <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
              <?php foreach (QR_SESSIONS as $type => $meta): ?>
                <?php $qr = $student['qrs'][$type] ?? null; ?>
                <div class="bg-white dark:bg-gray-800 p-4 rounded-xl shadow text-center space-y-2">
                  <p class="font-semibold text-sm"><?= $meta['label'] ?></p>
                  <?php if ($qr && $qr['code'] && file_exists($qr['file'])): ?>
                    <img src="<?= $qr['url'] ?>?<?= time() ?>" alt="<?= $meta['label'] ?>" class="w-28 h-28 mx-auto">
                    <p class="text-xs text-gray-600 dark:text-gray-300">Valid: <?= $meta['start'] ?> - <?= $meta['end'] ?></p>
                  <?php else: ?>
                    <p class="text-red-500 text-xs py-8">❗ Not generated.</p>
                  <?php endif; ?>
                </div>
              <?php endforeach; ?>
            </div>
          </div>
        <?php endif; ?>
      <?php endforeach; ?>
      <p class="text-xs text-gray-500">Each QR code is valid only for the student it was generated for and appears automatically at its scheduled time (07:30, 12:00, 13:00, 17:00).</p>
    <?php else: ?>
      <div class="bg-yellow-100 dark:bg-yellow-900 text-yellow-800 dark:text-yellow-200 p-4 rounded mb-4">
        ⚠️ QR codes appear automatically at their scheduled times (07:30 AM, 12:00 PM, 01:00 PM, 05:00 PM). If none are showing, make sure the cron job is running.
      </div>
    <?php endif; ?>
  </div>

  <div class="mt-8">
    <h3 class="text-xl font-semibold mb-4">Student Assistants - <?= htmlspecialchars($user['office']) ?> Office</h3>
    <?php if (empty($students)): ?>
      <p class="text-gray-600 dark:text-gray-400">No student assistants found for your office.</p>
    <?php else: ?>
      <div class="overflow-x-auto">
        <table class="w-full bg-white dark:bg-gray-800 border rounded">
          <thead class="bg-blue-100 dark:bg-gray-700">
            <tr>
              <th class="text-left p-3">Full Name</th>
              <th class="text-left p-3">Username</th>
              <th class="text-left p-3">Email</th>
              <th class="text-left p-3">Status</th>
              <th class="text-left p-3">Created</th>
            </tr>
          </thead>
          <tbody>
            <?php foreach ($students as $student): ?>
              <tr class="border-t hover:bg-blue-50 dark:hover:bg-gray-700">
                <td class="p-3"><?= htmlspecialchars($student['fullname']) ?></td>
                <td class="p-3"><?= htmlspecialchars($student['username']) ?></td>
                <td class="p-3"><?= htmlspecialchars($student['email']) ?></td>
                <td class="p-3"><?= htmlspecialchars($student['status']) ?></td>
                <td class="p-3 text-sm text-gray-500"><?= htmlspecialchars(date('M d, Y', strtotime($student['created_at']))) ?></td>
              </tr>
            <?php endforeach ?>
          </tbody>
        </table>
      </div>
    <?php endif ?>
  </div>
</main>

<footer class="text-center p-4 text-sm text-gray-600 dark:text-gray-400">
  MySchedMate &copy; <?= date('Y') ?>
</footer>

<script>
  const toggleBtn = document.getElementById('theme-toggle');
  const htmlEl = document.documentElement;
  const icon = document.getElementById('theme-icon');

  toggleBtn.addEventListener('click', () => {
    htmlEl.classList.toggle('dark');
    icon.setAttribute('data-lucide', htmlEl.classList.contains('dark') ? 'sun' : 'moon');
    lucide.createIcons();
  });

  lucide.createIcons();
</script>

</body>
</html>
