<?php
require_once __DIR__ . '/db.php';
require_once __DIR__ . '/phpqrcode/qrlib.php';

// The four daily QR codes, their scan windows, and the exact
// time each one is auto-generated by the cron job.
define('QR_SESSIONS', [
  'morning_in'    => ['label' => 'AM Time In',    'start' => '07:30', 'end' => '12:00', 'gen_at' => '07:30'],
  'morning_out'   => ['label' => 'AM Time Out',   'start' => '07:30', 'end' => '12:00', 'gen_at' => '12:00'],
  'afternoon_in'  => ['label' => 'PM Time In',    'start' => '13:00', 'end' => '17:00', 'gen_at' => '13:00'],
  'afternoon_out' => ['label' => 'PM Time Out',   'start' => '13:00', 'end' => '17:00', 'gen_at' => '17:00'],
]);

// QR type -> attendance_logs column
define('QR_COLUMN_MAP', [
  'morning_in'    => 'morning_time_in',
  'morning_out'   => 'morning_time_out',
  'afternoon_in'  => 'afternoon_time_in',
  'afternoon_out' => 'afternoon_time_out',
]);

// Filesystem location of QR PNGs (repo-root/assets/qrcodes)
define('QR_DIR', __DIR__ . '/../assets/qrcodes');

// Filesystem path of a student's QR PNG
function qrFilePath($date, $type, $userId) {
  return QR_DIR . '/' . str_replace('-', '', $date) . '_' . $type . '_u' . $userId . '.png';
}

// Web URL of a student's QR PNG (relative to admin/ pages)
function qrFileUrl($date, $type, $userId) {
  return '../assets/qrcodes/' . str_replace('-', '', $date) . '_' . $type . '_u' . $userId . '.png';
}

// Lists the students to generate QRs for.
// $userId: a single student, or null for ALL students (cron).
function qrStudents($userId = null) {
  global $pdo;
  if ($userId !== null) {
    $stmt = $pdo->prepare("SELECT id, fullname FROM users WHERE id = ? AND role = 'student'");
    $stmt->execute([$userId]);
    return $stmt->fetchAll();
  }
  $stmt = $pdo->prepare("SELECT id, fullname FROM users WHERE role = 'student' ORDER BY fullname");
  $stmt->execute();
  return $stmt->fetchAll();
}

// Generates (or regenerates) the four QR codes per student for the given date.
// Each QR is bound to one student (user_id) so only that student can scan it.
// $userId: single student, or null for all students.
// $types: optional array of qr_type to generate (used by the cron job).
// Idempotent (REPLACE INTO).
function generateDailyQrCodes($date = null, $userId = null, $types = null) {
  global $pdo;
  $date = $date ?: date('Y-m-d');

  if (!file_exists(QR_DIR)) {
    mkdir(QR_DIR, 0777, true);
  }

  $students = qrStudents($userId);
  $result = [];

  foreach ($students as $student) {
    $result[$student['id']] = [
      'name' => $student['fullname'],
      'qrs' => [],
    ];

    foreach (QR_SESSIONS as $type => $meta) {
      if ($types !== null && !in_array($type, $types, true)) {
        continue;
      }

      $code = uniqid("QR_{$type}_", true);
      $expiresAt = $date . ' ' . $meta['end'] . ':00';
      $file = qrFilePath($date, $type, $student['id']);

      QRcode::png($code, $file);

      $stmt = $pdo->prepare("REPLACE INTO qr_codes (date_generated, user_id, qr_type, code, expires_at) VALUES (?, ?, ?, ?, ?)");
      $stmt->execute([$date, $student['id'], $type, $code, $expiresAt]);

      $result[$student['id']]['qrs'][$type] = [
        'type' => $type,
        'label' => $meta['label'],
        'start' => $meta['start'],
        'end' => $meta['end'],
        'gen_at' => $meta['gen_at'],
        'code' => $code,
        'expires_at' => $expiresAt,
        'file' => $file,
        'url' => qrFileUrl($date, $type, $student['id']),
      ];
    }
  }

  return $result;
}

// Auto-generates, for every student, the QR types whose scheduled
// generation time has been reached but which are not yet in the DB.
// The cron job calls this every minute; it is a cheap no-op most runs
// and creates each QR at its exact time (07:30 / 12:00 / 13:00 / 17:00).
function generateDueQrCodes($date = null) {
  global $pdo;
  $date = $date ?: date('Y-m-d');

  $result = [];

  foreach (qrStudents() as $student) {
    $stmt = $pdo->prepare("SELECT qr_type FROM qr_codes WHERE date_generated = ? AND user_id = ?");
    $stmt->execute([$date, $student['id']]);
    $have = $stmt->fetchAll(PDO::FETCH_COLUMN);

    $due = [];
    foreach (QR_SESSIONS as $type => $meta) {
      if (time() >= strtotime($date . ' ' . $meta['gen_at']) && !in_array($type, $have, true)) {
        $due[] = $type;
      }
    }

    if ($due) {
      $result[$student['id']] = generateDailyQrCodes($date, $student['id'], $due)[$student['id']];
    }
  }

  return $result;
}

// Fetches QR info for display, grouped per student.
// $userId: a single student, or null for all students.
function getDailyQrCodes($date = null, $userId = null) {
  global $pdo;
  $date = $date ?: date('Y-m-d');

  if ($userId !== null) {
    $stmt = $pdo->prepare("
      SELECT q.user_id, u.fullname, q.qr_type, q.code, q.expires_at
      FROM qr_codes q
      JOIN users u ON u.id = q.user_id
      WHERE q.date_generated = ? AND q.user_id = ?
    ");
    $stmt->execute([$date, $userId]);
  } else {
    $stmt = $pdo->prepare("
      SELECT q.user_id, u.fullname, q.qr_type, q.code, q.expires_at
      FROM qr_codes q
      JOIN users u ON u.id = q.user_id
      WHERE q.date_generated = ?
    ");
    $stmt->execute([$date]);
  }
  $rows = $stmt->fetchAll();

  $result = [];
  foreach ($rows as $r) {
    if (!isset($result[$r['user_id']])) {
      $result[$r['user_id']] = ['name' => $r['fullname'], 'qrs' => []];
    }
    $result[$r['user_id']]['qrs'][$r['qr_type']] = [
      'type' => $r['qr_type'],
      'label' => QR_SESSIONS[$r['qr_type']]['label'],
      'start' => QR_SESSIONS[$r['qr_type']]['start'],
      'end' => QR_SESSIONS[$r['qr_type']]['end'],
      'code' => $r['code'],
      'expires_at' => $r['expires_at'],
      'file' => qrFilePath($date, $r['qr_type'], $r['user_id']),
      'url' => qrFileUrl($date, $r['qr_type'], $r['user_id']),
    ];
  }

  return $result;
}
